-- 癒見｜Supabase / PostgreSQL Schema
-- 可直接貼到 Supabase SQL Editor 執行

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'editor',
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  city TEXT NOT NULL,
  district TEXT DEFAULT '', address TEXT DEFAULT '', phone TEXT DEFAULT '',
  website TEXT DEFAULT '', booking_url TEXT DEFAULT '', email TEXT DEFAULT '',
  description TEXT DEFAULT '', services TEXT DEFAULT '', service_hours TEXT DEFAULT '',
  service_area TEXT DEFAULT '', lat DOUBLE PRECISION, lng DOUBLE PRECISION,
  image_path TEXT DEFAULT '', verified INTEGER NOT NULL DEFAULT 0 CHECK (verified IN (0,1)),
  featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0,1)),
  source_note TEXT DEFAULT '', published INTEGER NOT NULL DEFAULT 1 CHECK (published IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL, title TEXT NOT NULL, category TEXT DEFAULT '',
  summary TEXT DEFAULT '', body TEXT DEFAULT '', author TEXT DEFAULT '平台編輯團隊',
  reviewer TEXT DEFAULT '', references_text TEXT DEFAULT '', conflict_disclosure TEXT DEFAULT '',
  cover_image TEXT DEFAULT '', sponsored INTEGER NOT NULL DEFAULT 0 CHECK (sponsored IN (0,1)),
  featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0,1)),
  meta_title TEXT DEFAULT '', meta_description TEXT DEFAULT '',
  published INTEGER NOT NULL DEFAULT 1 CHECK (published IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS experts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, role_title TEXT NOT NULL, specialty TEXT DEFAULT '', organization TEXT DEFAULT '',
  bio TEXT DEFAULT '', image_path TEXT DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0,
  published INTEGER NOT NULL DEFAULT 1 CHECK (published IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS navigator_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL, help_text TEXT DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0,
  published INTEGER NOT NULL DEFAULT 1 CHECK (published IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS navigator_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES navigator_questions(id) ON DELETE CASCADE,
  label TEXT NOT NULL, risk_level INTEGER NOT NULL DEFAULT 0, sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS partner_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, organization TEXT DEFAULT '', email TEXT DEFAULT '', phone TEXT DEFAULT '',
  inquiry_type TEXT DEFAULT '', message TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL, source TEXT DEFAULT 'website',
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  username TEXT DEFAULT '', action TEXT NOT NULL, entity_type TEXT DEFAULT '', entity_id BIGINT,
  detail TEXT DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_resources_public ON resources (published, featured, verified, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_public ON articles (published, featured, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_category ON articles (category);
CREATE INDEX IF NOT EXISTS idx_experts_sort ON experts (published, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_id_desc ON audit_logs (id DESC);


-- 匿名網站流量統計：不儲存原始 IP，只使用第一方隨機 visitor_id Cookie。
CREATE TABLE IF NOT EXISTS traffic_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id TEXT NOT NULL,
  path TEXT NOT NULL,
  referrer_host TEXT DEFAULT '',
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_traffic_events_viewed_at ON traffic_events (viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_traffic_events_visitor_id ON traffic_events (visitor_id);
CREATE INDEX IF NOT EXISTS idx_traffic_events_path ON traffic_events (path);
